#!/bin/bash

# =============================================================================
# UPLOAD SANITIZED DATABASE TO S3 AND CLEANUP
# =============================================================================
# Purpose: Upload exported sanitized database files to S3 bucket,
#          clean up all local exported files, and drop the local database
# Usage: ./upload_s3.sh <database_name> <local_folder>
# Example: ./upload_s3.sh yp /Users/reuel/database/
# Requirements:
#   - AWS CLI installed and configured with appropriate credentials
#   - PostgreSQL installed (for dropdb command)
#   - Exported files must exist in local_folder
# Author: Database Team
# Last Modified: 2026-02-13
# =============================================================================

set -e  # Exit on any error
set -u  # Exit on undefined variable

# -----------------------------------------------------------------------------
# COLORS FOR OUTPUT
# -----------------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info()    { echo -e "${GREEN}[INFO]${NC} $1"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_step()    { echo -e "${BLUE}[STEP]${NC} $1"; }

# -----------------------------------------------------------------------------
# VALIDATE ARGUMENTS
# -----------------------------------------------------------------------------
if [ $# -lt 2 ]; then
    log_error "Usage: $0 <database_name> <local_folder>"
    log_error "Example: $0 yp /Users/reuel/database/"
    exit 1
fi

# -----------------------------------------------------------------------------
# CONFIGURATION
# -----------------------------------------------------------------------------
DB_NAME=$1
LOCAL_FOLDER=$2

# S3 bucket destination URI
S3_BUCKET="s3://ysc-backup-databases/sanitized-yp/"

# PostgreSQL connection details
DB_HOST=${DB_HOST:-localhost}
DB_PORT=${DB_PORT:-5432}
DB_USER=${DB_USER:-postgres}
DB_PASSWORD=${DB_PASSWORD:-}

# -----------------------------------------------------------------------------
# DISPLAY HEADER
# -----------------------------------------------------------------------------
echo ""
log_info "=========================================="
log_info "S3 Upload and Cleanup Process"
log_info "=========================================="
log_info "Database:     $DB_NAME"
log_info "Local Folder: $LOCAL_FOLDER"
log_info "S3 Bucket:    $S3_BUCKET"
log_info "=========================================="
echo ""

# -----------------------------------------------------------------------------
# STEP 1: VERIFY AWS CLI IS AVAILABLE
# -----------------------------------------------------------------------------
log_step "[1/6] Checking AWS CLI..."

if ! command -v aws &> /dev/null; then
    log_error "AWS CLI is not installed or not in PATH"
    log_error "Install it from: https://aws.amazon.com/cli/"
    exit 1
fi

# Verify AWS credentials are configured
if ! aws sts get-caller-identity &> /dev/null; then
    log_error "AWS credentials are not configured or invalid"
    log_error "Run: aws configure"
    exit 1
fi

log_info "✓ AWS CLI is available"
echo ""

# -----------------------------------------------------------------------------
# STEP 2: LOCATE EXPORTED FILES
# -----------------------------------------------------------------------------
# Files generated by export_db.sh:
#   - <db_name>_sanitized_<timestamp>.sql.gz   (main archive)
#   - <db_name>_sanitized_<timestamp>.sql.gz.md5
#   - <db_name>_sanitized_<timestamp>.sql.gz.sha256
#   - <db_name>_sanitized_<timestamp>.sql.gz.info
# -----------------------------------------------------------------------------
log_step "[2/6] Locating exported files in $LOCAL_FOLDER..."

# Find the most recent sanitized sql.gz file
SQL_GZ_FILE=$(ls -t "${LOCAL_FOLDER}"${DB_NAME}_sanitized_*.sql.gz 2>/dev/null | head -1)

# Check if file exists
if [ -z "$SQL_GZ_FILE" ]; then
    log_error "No exported file found matching: ${LOCAL_FOLDER}${DB_NAME}_sanitized_*.sql.gz"
    log_error "Please run export_db.sh first"
    exit 1
fi

# Derive the other file paths based on the main file name
MD5_FILE="${SQL_GZ_FILE}.md5"
SHA256_FILE="${SQL_GZ_FILE}.sha256"
INFO_FILE="${SQL_GZ_FILE}.info"

# Display found files
log_info "Found files:"
log_info "  Archive:  $SQL_GZ_FILE"
[ -f "$MD5_FILE" ]    && log_info "  MD5:      $MD5_FILE"    || log_warning "  MD5:      not found (skipping)"
[ -f "$SHA256_FILE" ] && log_info "  SHA256:   $SHA256_FILE" || log_warning "  SHA256:   not found (skipping)"
[ -f "$INFO_FILE" ]   && log_info "  Info:     $INFO_FILE"   || log_warning "  Info:     not found (skipping)"
echo ""

# -----------------------------------------------------------------------------
# STEP 3: UPLOAD FILES TO S3
# -----------------------------------------------------------------------------
log_step "[3/6] Uploading files to S3..."
UPLOAD_FAILED=false

# Upload main sql.gz archive
log_info "Uploading archive: $(basename $SQL_GZ_FILE)"
if aws s3 cp "$SQL_GZ_FILE" "$S3_BUCKET"; then
    log_info "✓ Archive uploaded successfully"
else
    log_error "✗ Failed to upload archive"
    UPLOAD_FAILED=true
fi

# If main archive upload failed, stop here - don't cleanup local files
if [ "$UPLOAD_FAILED" = true ]; then
    log_error "Main archive upload failed. Aborting cleanup to prevent data loss."
    exit 1
fi

echo ""

# -----------------------------------------------------------------------------
# STEP 4: VERIFY UPLOAD IN S3
# -----------------------------------------------------------------------------
log_step "[4/6] Verifying upload in S3..."

S3_FILENAME=$(basename "$SQL_GZ_FILE")

if aws s3 ls "${S3_BUCKET}${S3_FILENAME}" &> /dev/null; then
    log_info "✓ File verified in S3: ${S3_BUCKET}${S3_FILENAME}"
else
    log_error "✗ File not found in S3 after upload. Aborting cleanup."
    exit 1
fi

echo ""

# -----------------------------------------------------------------------------
# STEP 5: CLEANUP LOCAL EXPORTED FILES
# -----------------------------------------------------------------------------
log_step "[5/6] Cleaning up local exported files..."

# Remove main archive
if [ -f "$SQL_GZ_FILE" ]; then
    rm -f "$SQL_GZ_FILE"
    log_info "✓ Removed: $(basename $SQL_GZ_FILE)"
fi

# Remove MD5 file
if [ -f "$MD5_FILE" ]; then
    rm -f "$MD5_FILE"
    log_info "✓ Removed: $(basename $MD5_FILE)"
fi

# Remove SHA256 file
if [ -f "$SHA256_FILE" ]; then
    rm -f "$SHA256_FILE"
    log_info "✓ Removed: $(basename $SHA256_FILE)"
fi

# Remove info file
if [ -f "$INFO_FILE" ]; then
    rm -f "$INFO_FILE"
    log_info "✓ Removed: $(basename $INFO_FILE)"
fi

echo ""

# -----------------------------------------------------------------------------
# STEP 6: DROP LOCAL DATABASE
# -----------------------------------------------------------------------------
log_step "[6/6] Dropping local database: $DB_NAME..."

if PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" \
    -c "SELECT 1" -d "$DB_NAME" &> /dev/null; then

    # Terminate all active connections to the database before dropping
    log_info "Terminating active connections to $DB_NAME..."
    PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d postgres \
        -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '$DB_NAME' AND pid <> pg_backend_pid();" \
        &> /dev/null

    # Drop the database
    if PGPASSWORD="$DB_PASSWORD" dropdb -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" "$DB_NAME"; then
        log_info "✓ Database '$DB_NAME' dropped successfully"
    else
        log_error "✗ Failed to drop database '$DB_NAME'"
        exit 1
    fi
else
    log_warning "Database '$DB_NAME' does not exist or already dropped, skipping..."
fi

echo ""

# -----------------------------------------------------------------------------
# SUMMARY
# -----------------------------------------------------------------------------
log_info "=========================================="
log_info "Upload and Cleanup Completed!"
log_info "=========================================="
log_info "Uploaded to:  ${S3_BUCKET}$(basename $SQL_GZ_FILE)"
log_info "Local files:  Removed"
log_info "Database:     Dropped"
log_info "=========================================="
echo ""

exit 0
